apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-scraper
  namespace: {{ .Values.namespace }}
  labels:
    app: ems-scraper
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ems-scraper
  template:
    metadata:
      labels:
        app: ems-scraper
    spec:
      containers:
      - name: ems-scraper
        image: {{ .Values.image.registry }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "mysql://root:$(MYSQL_PASSWORD)@mysql-service:3306/ems_scraper"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
#         livenessProbe: # TODO: re-enable when api is working
#           httpGet:
#             path: /api/status
#             port: 3000
#           initialDelaySeconds: 30
#           periodSeconds: 10
#         readinessProbe:
#           httpGet:
#             path: /api/status
#             port: 3000
#           initialDelaySeconds: 5
#           periodSeconds: 5